import enum

class disease_status(enum.Enum):
    VULNERABLE = 0
    INCUBATION = 1
    ASYMPTOMATIC = 2
    SYMPTOMATIC = 3
    IMMUNE = 4
    DEAD = 5

#simulation
X_LIMIT = 7500
Y_LIMIT = 7500
NUM_PEOPLE = 1000
SIM_HOURS = 5000
MAX_INFECTION_TIME = (24*14)
MAX_INCUBATION_TIME = (24*7)

NORMAL_INFECTTION_PROBABILTY = 0.5
MASKED_INFECTTION_PROBABILTY = 0.3
VACCINEATED_INFECTTION_PROBABILTY = 0.3
MASKED_VACCINEATED_INFECTTION_PROBABILTY = 0.1
NORMAL_ASYMPTOMATIC_PROBABILTY = 0.3
VACCINEATED_ASYMPTOMATIC_PROBABILTY = 0.5
MASKING_PERCENTAGE = 0.5
VACCINATION_PERCENTAGE = 0.5

NORMAL_FATALITY_RATE = 0.02
ATURATED_FATALITY_RATE = 0.06
INFECTION_PROXIMITY = 10
INITIAL_INFECTIONS = 5

SATURATION_THRESHOLD = (NUM_PEOPLE/5)

#location
CLOSE_ENOUGH = 0.05

#ppmodel
NUM_POPULAR_PLACES = 20

DISTANCING_PROBABILITY = 0.8

DISTANCING_HOME_PROBABILITY = 0.097
NOT_DISTANCING_HOME_PROBABILITY = 0.2

PP_TOP_SPEED = 30

MAX_STAY = 3*24